screenshot_props.top_left = [ 90, 435 ] # 1920x1080 in game HUD 100% (Default)
screenshot_props.next_offset = 90 # 1920x1080 in game HUD 100% (Default)

[screenshot_zones]
state.offset = [ 0, 0 ] # 1920x1080 in game HUD 100% (Default)
state.size = [ 75, 75 ] # 1920x1080 in game HUD 100% (Default)
state.threshold = 0.7

action.offset = [ 80, 10 ]
action.size = [ 32, 32 ]
action.threshold = 0.55
