[screenshot_props]
top_left = [ 80, 434 ]
next_offset = 77

[screenshot_zones]
state.offset = [ 0, 0 ]
state.size = [ 68, 68 ]
state.threshold = 0.7

action.offset = [ 80, 10 ]
action.size = [ 32, 32 ]
action.threshold = 0.55
